# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

os:
  - linux
  - osx

dist:
  - precise
  - xenial

r:
  - devel
  - release
  - oldrel

#r_github_packages:
#  - jackwasey/icd
